// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Position {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Position {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readFloat32(this.bb_pos);
}

y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

h():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

w():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createPosition(builder:flatbuffers.Builder, X: number, Y: number, H: number, W: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(W);
  builder.writeFloat32(H);
  builder.writeFloat32(Y);
  builder.writeFloat32(X);
  return builder.offset();
}

}
